INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'NTP', 'Network Time Protocol Version 3. RFC1305', '3', '', 5);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'SNTP', 'Simple Network Time Protocol (SNTP) RFC4330', '', '', 5);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'RFC1510', 'RFC1510 The Kerberos Network Authentication Service (V5)', '5', '', 5);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'CCOW', 'HL7 Context Management “CCOW”', '1.4', '', 4);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'HL7v2.3.1', 'HL7 Version 2.3.1', '2.3.1', '', 0);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'HL7v2.5', 'HL7 Version 2.5', '2.5', '', 0);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'URL', 'IETF RFC1738, Uniform Resource Locators (URL)', 'December 1994', 'http://www.faqs.org/rfcs/rfc1738.html', 4);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'HTTP', 'IETF RFC2616 HyperText Transfer Protocol HTTP/1.1', '1.1', '', 3);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'XML', 'Extensible Markup Language (XML) 1.0 (Second Edition). W3C Recommendation 6 October 2000', '', 'http://www.w3.org/TR/REC-xml', 4);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'WSDL', 'Web Services Description Language (WSDL) 1.1. W3C Note 15 March 2001', '', 'http://www.w3.org/TR/wsdl', 4);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'XHTML_1.0', 'XHTML 1.0 The Extensible HyperText Markup Language (Second Edition).A Reformulation of HTML 4 in XML 1.0. W3C Recommendation 26 January 2000, revised 1 August 2002.', '', 'http://www.w3.org/TR/xhtml1', 4);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'XHTML_Basic', 'XHTMLTM Basic. W3C Recommendation 19 December 2000', '', 'http://www.w3.org/TR/xhtml-basic', 4);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'ebRIM', 'OASIS/ebXML Registry Information Model v3.0', '3.0', '', 4);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'ebRS', 'OASIS/ebXML Registry Services Specifications v3.0', '3.0', '', 4);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'DICOM_PS3.15', 'DICOM PS 3.15-2011: Security Profiles. Annex B1: The Basic TLS Secure Transport Connection Profile.', '', 'http://dicom.nema.org/', 4);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'TLS', 'IETF: Transport Layer Security (TLS) 1.0 (RFC 2246)', '', '', 4);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'ITU-T', 'ITU-T: Recommendation X.509 (03/00). “Information technology - Open Systems Interconnection - The directory: Public-key and attribute certificate frameworks"', '', '', 4);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'S/MIME', 'RFC-3851 Secure/Multipurpose Internet Mail Extensions (S/MIME) Version 3.1 Message Specification', '', '', 4);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'SYSLOG_TLS', 'Transmission of Syslog Messages over TLS (RFC 5425)', '', '', 6);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'SYSLOG_UDP', 'Transmission of Syslog Messages over UDP (RFC 5426)', '', '', 6);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'RFC3881', 'Security Audit and Access Accountability Message XML Data Definiions for Healthcare Applications (RFC 3881)', '', '', 4);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'SYSLOG', 'The Syslog Protocol. (RFC 5424)', '', '', 6);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'E2147-01', 'E2147-01 Standard Specification for Audit and Disclosure Logs for Use in Health Information Systems.', '', '', 4);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'SP_800-92', 'SP 800-92 Guide to Computer Security Log Management', '', '', 4);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'DNS', 'RFC-2181 Clarifications to the DNS Specification', '', '', 4);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'DNS_ALIASES', 'RFC-2219 Use of DNS Aliases for Network Services', '', '', 4);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'DNS_SRV', 'RFC-2782 A DNS RR for specifying the location of services (DNS SRV)', '', '', 4);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'DICOM_Suppl67', 'DICOM Supplement 67 – Configuration Management, January 14, 2004', '', '', 4);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'RFC1766', 'RFC 1766 Tags for the Identification of Languages', '', '', 4);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'LDAPv3', 'RFC 2251 - Lightweight Directory Access Protocol (v3)', '', '', 5);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'RFC2252', 'RFC 2252 - Lightweight Directory Access Protocol (v3): Attribute Syntax Definitions', '', '', 4);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'RFC2253', 'RFC 2253 - Lightweight Directory Access Protocol (v3): UTF-8 String Representation of Distinguished Names', '', '', 4);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'RFC2256', 'RFC 2256 - A Summary of the X.500(96) User Schema for use with LDAPv3', '', '', 4);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'RFC2798', 'RFC 2798 - Definition of the inetOrgPerson LDAP Object Class', '', '', 4);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'RFC2829', 'RFC 2829 Authentication Methods for LDAP', '', '', 4);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'RFC2830', 'RFC 2830 LDAPv3: Extension for Transport Layer Security', '', '', 5);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'RFC3377', 'RFC 3377 - Lightweight Directory Access Protocol (v3): Technical Specification', '', '', 5);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'ISO17090', 'ISO/TS 17090 directory standard for healthcare identity management', '', '', 4);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'CRU', 'Projet de schémas d’annuaires et de schémas de registres de resources numériques interopérables pour les administrations Document technique – v1, novembre 2002', '', '', 4);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'E.123', 'E.123: Notation for national and international telephone numbers', '', '', 4);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'ITI_TF3', 'Metadata used in Document Sharing profiles', '', '', 4);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'DICOM_FILE_FORMAT', 'DICOM PS 3.10 Media Storage and File Format for Data Interchange (DICOM file format)', '', 'http://dicom.nema.org/', 4);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'DICOM_MEDIA_FORMAT', 'DICOM PS 3.12 Media Formats and Physical Media for Data Interchange', '', 'http://dicom.nema.org/', 4);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'MDN', 'MDN: RFC 3798 Message Disposition Notification', '', 'http://www.rfc-editor.org/rfc/rfc3798.txt', 5);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'IHE_WS', 'ITI TF-2x: Appendix V: Web Services for IHE Transactions.', '', '', 2);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'XForms', 'XForms 1.1, W3C Working Draft.', '', 'http://www.w3.org/TR/2004/WD-xforms11-20041115/', 4);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'MTOM', 'MTOM SOAP Message Transmission Optimization Mechanism', '', 'http://www.w3.org/TR/soap12-mtom/', 4);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'SAMLCore', 'SAMLCore SAML V2.0 Core standard', '', 'http://www.oasis-open.org/committees/security/', 4);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'WSS10', 'WSS10 OASIS Standard, "OASIS Web Services Security: SOAP Message Security 1.0 (WS-Security 2004)", March 2004.', '1.0', 'http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0.pdf', 4);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'WSS11', 'WSS11 OASIS Standard, "OASIS Web Services Security: SOAP Message Security 1.1 (WS-Security 2004)", February 2006.', '1.1', 'http://www.oasis-open.org/committees/download.php/16790/wss-v1.1-spec-os-SOAPMessageSecurity.pdf', 4);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'SAMLTokenProfile10', 'WSS:SAMLTokenProfile1.0 OASIS Standard, “Web Services Security: SAML Token Profile”, December 2004', '', 'http://docs.oasis-open.org/wss/oasis-wss-saml-token-profile-1.0.pdf', 4);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'SAMLTokenProfile11', 'WSS:SAMLTokenProfile1. 1 OASIS Standard, “Web Services Security: SAML Token Profile 1.1”, February 2006', '', 'http://www.oasis-open.org/committees/download.php/16768/wss-v1.1-spec-os-SAMLTokenProfile.pdf', 4);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'XSPA-SAML', 'XSPA-SAMLv1.0 OASIS Standard, “Cross-Enterprise Security and Privacy Authorization (XSPA) Profile of the Security Assertion Markup Language (SAML)  or Healthcare v1.0” , November 2009', '', '', 4);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'SAMLProfile20', 'SAML 2.0 Profile For XACML 2.0 OASIS Standard, February 2005', '', '', 4);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'XOP', 'XOP XML-binary Optimized Packaging', '', 'http://www.w3.org/TR/2005/REC-xop10-20050125/', 4);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'HL7v3', 'HL7 Version 3 Edition 2008', '', 'http://www.hl7.org/memonly/downloads/v3edition.cfm#V32008', 2);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'POSIX_1003.2', 'POSIX 1003.2 : IEEE Std 1003.2 IEEE Standard for Information Technology — Portable Operating System Interface (POSIX®) — Part 2: Shell and Utilities — Amendment 1: Batch Environment -Description', '', '', 4);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'HL7v2.5.1', 'HL7 Version 2.5.1', '2.5.1', '', 0);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'DICOM_MWL', 'DICOM 2011 PS 3.4 Modality Worklist SOP Class', '', '', 1);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'DICOM_MPPS', 'DICOM 2011 PS 3.4: Modality Performed Procedure Step SOP Class', '', '', 1);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'DICOM_DCMR', 'DICOM 2011 PS 3.16: DCMR Context Groups (Normative)', '', '', 4);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'DICOM_STORAGE', 'DICOM 2011 PS 3.4: Storage Service Class.', '', '', 1);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'DICOM_GSPS', 'DICOM 2011 PS 3.4: Grayscale Softcopy Presentation State Storage', '', '', 4);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'DICOM_GSDF', 'DICOM 2011 PS 3.14: Grayscale Standard Display Function', '', '', 4);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'DICOM_COMMIT', 'DICOM 2011 PS 3.4: Storage Commitment Push Model SOP Class', '', '', 1);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'DICOM_QR', 'DICOM 2011 PS 3.4: Query/Retrieve Service Class', '', '', 1);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'DICOM_PRINT', 'DICOM 2011 PS 3.4: Print Management Service Class', '', '', 1);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'DICOM_LUT', 'DICOM 2011 PS 3.4: Presentation LUT SOP Class', '', '', 4);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'DICOM_CMR', 'DICOM 2011 PS 3.16: Content Mapping Resource', '', '', 4);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'DICOM_KOS', 'DICOM 2011 PS 3.4: Key Object Selection Document Storage SOP Class', '', '', 1);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'DICOM_KIN', 'DICOM 2011 PS 3.4: Key Image Note Storage SOP Class', '', '', 1);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'DICOM_GPWL', 'DICOM 2011 PS 3.4: General Purpose Worklist SOP Class', '', '', 1);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'DICOM_GPSPS', 'DICOM 2011 PS 3.4: General Purpose Scheduled Procedure Step SOP Class', '', '', 1);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'DICOM_GPPPS', 'DICOM 2011 PS 3.4: General Purpose Performed Procedure Step SOP Clas', '', '', 1);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'DICOM_MEDIA_STORAGE_PROFILE', 'DICOM 2011 PS 3.11: Media Storage Application Profiles', '', '', 4);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'DICOM_Suppl80', 'DICOM Supplement 80 (final text): DVD Media Application Profiles', '', '', 4);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'HL7v2.4', 'HL7 Version 2.4', '2.4', '', 0);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'DICOM_IAN', 'DICOM 2011 PS 3.4: Instance Availability Notification Service Class', '', '', 1);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'DICOM_BALCP', 'DICOM 2011 PS 3.15: Basic Application Level Confidentiality Profile.', '', '', 4);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'DICOM_IOD', 'DICOM 2011 PS 3.3: Information Object Definitions', '', '', 4);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'WADO', 'DICOM 2011 PS 3.18: Web Access to DICOM Persistent Objects (WADO)', '', '', 2);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'DICOM_SIO', 'DICOM 2011 PS 3.3 SOP Information Objects, Common Module Attribute', '', '', 4);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'DICOM_X_DOSE', 'DICOM 2011 PS 3.3: A.35.8 X-Ray Radiation Dose SR IOD', '', '', 1);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'DICOM_SR', 'DICOM 2011 PS 3.4: Structured Reporting Storage SOP Classes', '', '', 1);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'DICOM_X_DOSE_TPL', 'DICOM 2011 PS 3.16: X-Ray Radiation Dose SR IOD Templates', '', '', 4);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'DICOM_CT_DOSE_TPL', 'DICOM 2011 PS 3.16: CT Radiation Dose SR IOD Templates', '', '', 4);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'DICOM_DOSE_UC', 'DICOM 2011 PS 3.17: Annex AA: Radiation Dose Reporting Use Cases', '', '', 4);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'FTP_TLS', 'IETF RFC-4217 Securing FTP with TLS', '', '', 5);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'DICOM_TID', 'DICOM 2011 PS 3.16: TID 2010, CID 7011', '', '', 4);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'POCT1-A', 'POCT1-A: Device Message Layer (DML) defined in Appendix B of POCT1-A standard. ', '', '', 5);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'HL7v2.6', 'HL7 Version 2.6', '2.6', '', 0);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'DICOM_Suppl122', 'Supplement 122: Specimen Identification and Revised Pathology SOP Classes
1795 Revision: 12 – 2007/05/05', '', '', 4);
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-1'), (select id from tf_standard where keyword = 'NTP'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-1'), (select id from tf_standard where keyword = 'SNTP'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-3'), (select id from tf_standard where keyword = 'RFC1510'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-2'), (select id from tf_standard where keyword = 'RFC1510'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-4'), (select id from tf_standard where keyword = 'RFC1510'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-5'), (select id from tf_standard where keyword = 'CCOW'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-6'), (select id from tf_standard where keyword = 'CCOW'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-7'), (select id from tf_standard where keyword = 'CCOW'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-8'), (select id from tf_standard where keyword = 'HL7v2.3.1'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-9'), (select id from tf_standard where keyword = 'HL7v2.5'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-10'), (select id from tf_standard where keyword = 'HL7v2.5'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-11'), (select id from tf_standard where keyword = 'URL'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-11'), (select id from tf_standard where keyword = 'HTTP'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-11'), (select id from tf_standard where keyword = 'XML'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-11'), (select id from tf_standard where keyword = 'WSDL'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-11'), (select id from tf_standard where keyword = 'XHTML_1.0'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-11'), (select id from tf_standard where keyword = 'XHTML_Basic'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-12'), (select id from tf_standard where keyword = 'HTTP'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-12'), (select id from tf_standard where keyword = 'XML'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-12'), (select id from tf_standard where keyword = 'WSDL'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-13'), (select id from tf_standard where keyword = 'CCOW'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-18'), (select id from tf_standard where keyword = 'ebRIM'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-18'), (select id from tf_standard where keyword = 'ebRS'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-19'), (select id from tf_standard where keyword = 'DICOM_PS3.15'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-19'), (select id from tf_standard where keyword = 'TLS'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-19'), (select id from tf_standard where keyword = 'ITU-T'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-19'), (select id from tf_standard where keyword = 'S/MIME'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-20'), (select id from tf_standard where keyword = 'SYSLOG_TLS'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-20'), (select id from tf_standard where keyword = 'SYSLOG_UDP'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-20'), (select id from tf_standard where keyword = 'RFC3881'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-20'), (select id from tf_standard where keyword = 'SYSLOG'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-20'), (select id from tf_standard where keyword = 'E2147-01'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-20'), (select id from tf_standard where keyword = 'SP_800-92'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-20'), (select id from tf_standard where keyword = 'XML'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-21'), (select id from tf_standard where keyword = 'HL7v2.5'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-22'), (select id from tf_standard where keyword = 'HL7v2.5'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-23'), (select id from tf_standard where keyword = 'DNS'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-23'), (select id from tf_standard where keyword = 'DNS_ALIASES'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-23'), (select id from tf_standard where keyword = 'DNS_SRV'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-23'), (select id from tf_standard where keyword = 'DICOM_Suppl67'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-24'), (select id from tf_standard where keyword = 'RFC1766'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-24'), (select id from tf_standard where keyword = 'LDAPv3'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-24'), (select id from tf_standard where keyword = 'RFC2252'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-24'), (select id from tf_standard where keyword = 'RFC2253'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-24'), (select id from tf_standard where keyword = 'RFC2256'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-24'), (select id from tf_standard where keyword = 'RFC2798'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-24'), (select id from tf_standard where keyword = 'RFC2829'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-24'), (select id from tf_standard where keyword = 'RFC2830'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-24'), (select id from tf_standard where keyword = 'RFC3377'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-24'), (select id from tf_standard where keyword = 'ISO17090'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-24'), (select id from tf_standard where keyword = 'CRU'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-24'), (select id from tf_standard where keyword = 'E.123'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-30'), (select id from tf_standard where keyword = 'HL7v2.5'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-31'), (select id from tf_standard where keyword = 'HL7v2.5'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-32'), (select id from tf_standard where keyword = 'ITI_TF3'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-32'), (select id from tf_standard where keyword = 'DICOM_FILE_FORMAT'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-32'), (select id from tf_standard where keyword = 'DICOM_MEDIA_FORMAT'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-32'), (select id from tf_standard where keyword = 'MDN'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-32'), (select id from tf_standard where keyword = 'XHTML_1.0'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-32'), (select id from tf_standard where keyword = 'XHTML_Basic'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-34'), (select id from tf_standard where keyword = 'URL'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-34'), (select id from tf_standard where keyword = 'IHE_WS'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-34'), (select id from tf_standard where keyword = 'HTTP'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-34'), (select id from tf_standard where keyword = 'XML'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-34'), (select id from tf_standard where keyword = 'XForms'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-34'), (select id from tf_standard where keyword = 'XHTML_1.0'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-34'), (select id from tf_standard where keyword = 'XHTML_Basic'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-35'), (select id from tf_standard where keyword = 'IHE_WS'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-35'), (select id from tf_standard where keyword = 'HTTP'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-35'), (select id from tf_standard where keyword = 'XML'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-35'), (select id from tf_standard where keyword = 'URL'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-36'), (select id from tf_standard where keyword = 'URL'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-36'), (select id from tf_standard where keyword = 'HTTP'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-36'), (select id from tf_standard where keyword = 'IHE_WS'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-37'), (select id from tf_standard where keyword = 'URL'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-37'), (select id from tf_standard where keyword = 'IHE_WS'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-37'), (select id from tf_standard where keyword = 'HTTP'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-37'), (select id from tf_standard where keyword = 'XML'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-37'), (select id from tf_standard where keyword = 'XForms'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-38'), (select id from tf_standard where keyword = 'ebRIM'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-38'), (select id from tf_standard where keyword = 'ebRS'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-38'), (select id from tf_standard where keyword = 'IHE_WS'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-38'), (select id from tf_standard where keyword = 'ITI_TF3'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-39'), (select id from tf_standard where keyword = 'MTOM'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-39'), (select id from tf_standard where keyword = 'ITI_TF3'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-39'), (select id from tf_standard where keyword = 'IHE_WS'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-39'), (select id from tf_standard where keyword = 'ebRIM'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-39'), (select id from tf_standard where keyword = 'ebRS'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-40'), (select id from tf_standard where keyword = 'SAMLCore'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-40'), (select id from tf_standard where keyword = 'WSS10'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-40'), (select id from tf_standard where keyword = 'WSS11'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-40'), (select id from tf_standard where keyword = 'SAMLTokenProfile10'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-40'), (select id from tf_standard where keyword = 'SAMLTokenProfile11'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-40'), (select id from tf_standard where keyword = 'XSPA-SAML'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-40'), (select id from tf_standard where keyword = 'SAMLProfile20'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-41'), (select id from tf_standard where keyword = 'XOP'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-41'), (select id from tf_standard where keyword = 'ebRIM'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-41'), (select id from tf_standard where keyword = 'ebRS'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-41'), (select id from tf_standard where keyword = 'IHE_WS'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-41'), (select id from tf_standard where keyword = 'ITI_TF3'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-41'), (select id from tf_standard where keyword = 'MTOM'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-42'), (select id from tf_standard where keyword = 'ebRIM'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-42'), (select id from tf_standard where keyword = 'ebRS'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-42'), (select id from tf_standard where keyword = 'HL7v2.5'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-42'), (select id from tf_standard where keyword = 'IHE_WS'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-42'), (select id from tf_standard where keyword = 'ITI_TF3'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-43'), (select id from tf_standard where keyword = 'XOP'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-43'), (select id from tf_standard where keyword = 'ebRIM'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-43'), (select id from tf_standard where keyword = 'ebRS'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-43'), (select id from tf_standard where keyword = 'IHE_WS'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-43'), (select id from tf_standard where keyword = 'ITI_TF3'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-43'), (select id from tf_standard where keyword = 'MTOM'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-44'), (select id from tf_standard where keyword = 'HL7v3'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-44'), (select id from tf_standard where keyword = 'IHE_WS'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-45'), (select id from tf_standard where keyword = 'HL7v3'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-45'), (select id from tf_standard where keyword = 'IHE_WS'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-46'), (select id from tf_standard where keyword = 'HL7v3'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-46'), (select id from tf_standard where keyword = 'IHE_WS'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-47'), (select id from tf_standard where keyword = 'HL7v3'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-47'), (select id from tf_standard where keyword = 'IHE_WS'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-48'), (select id from tf_standard where keyword = 'XML'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-48'), (select id from tf_standard where keyword = 'HL7v3'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-48'), (select id from tf_standard where keyword = 'IHE_WS'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-51'), (select id from tf_standard where keyword = 'IHE_WS'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-51'), (select id from tf_standard where keyword = 'ebRIM'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-51'), (select id from tf_standard where keyword = 'ebRS'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-51'), (select id from tf_standard where keyword = 'ITI_TF3'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-55'), (select id from tf_standard where keyword = 'IHE_WS'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-55'), (select id from tf_standard where keyword = 'HL7v3'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-60'), (select id from tf_standard where keyword = 'HL7v3'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-60'), (select id from tf_standard where keyword = 'POSIX_1003.2'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-60'), (select id from tf_standard where keyword = 'IHE_WS'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-60'), (select id from tf_standard where keyword = 'HTTP'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-61'), (select id from tf_standard where keyword = 'ebRIM'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-61'), (select id from tf_standard where keyword = 'ebRS'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-61'), (select id from tf_standard where keyword = 'ITI_TF3'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-61'), (select id from tf_standard where keyword = 'IHE_WS'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-61'), (select id from tf_standard where keyword = 'HL7v2.5'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-1'), (select id from tf_standard where keyword = 'HL7v2.3.1'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-1'), (select id from tf_standard where keyword = 'HL7v2.5.1'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-2'), (select id from tf_standard where keyword = 'HL7v2.3.1'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-2'), (select id from tf_standard where keyword = 'HL7v2.5.1'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-3'), (select id from tf_standard where keyword = 'HL7v2.3.1'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-3'), (select id from tf_standard where keyword = 'HL7v2.5.1'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-4'), (select id from tf_standard where keyword = 'HL7v2.3.1'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-4'), (select id from tf_standard where keyword = 'HL7v2.5.1'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-5'), (select id from tf_standard where keyword = 'DICOM_MWL'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-6'), (select id from tf_standard where keyword = 'DICOM_MPPS'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-7'), (select id from tf_standard where keyword = 'DICOM_MPPS'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-7'), (select id from tf_standard where keyword = 'DICOM_DCMR'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-8'), (select id from tf_standard where keyword = 'DICOM_STORAGE'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-9'), (select id from tf_standard where keyword = 'DICOM_GSPS'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-9'), (select id from tf_standard where keyword = 'DICOM_GSDF'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-9'), (select id from tf_standard where keyword = 'DICOM_STORAGE'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-10'), (select id from tf_standard where keyword = 'DICOM_COMMIT'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-11'), (select id from tf_standard where keyword = 'DICOM_QR'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-12'), (select id from tf_standard where keyword = 'HL7v2.3.1'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-12'), (select id from tf_standard where keyword = 'HL7v2.5.1'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-13'), (select id from tf_standard where keyword = 'HL7v2.3.1'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-13'), (select id from tf_standard where keyword = 'HL7v2.5.1'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-14'), (select id from tf_standard where keyword = 'DICOM_QR'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-15'), (select id from tf_standard where keyword = 'DICOM_QR'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-15'), (select id from tf_standard where keyword = 'DICOM_GSDF'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-16'), (select id from tf_standard where keyword = 'DICOM_QR'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-16'), (select id from tf_standard where keyword = 'DICOM_STORAGE'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-17'), (select id from tf_standard where keyword = 'DICOM_GSPS'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-17'), (select id from tf_standard where keyword = 'DICOM_GSDF'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-17'), (select id from tf_standard where keyword = 'DICOM_QR'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-18'), (select id from tf_standard where keyword = 'DICOM_STORAGE'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-19'), (select id from tf_standard where keyword = 'DICOM_STORAGE'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-19'), (select id from tf_standard where keyword = 'DICOM_GSPS'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-19'), (select id from tf_standard where keyword = 'DICOM_GSDF'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-20'), (select id from tf_standard where keyword = 'DICOM_MPPS'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-21'), (select id from tf_standard where keyword = 'DICOM_MPPS'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-23'), (select id from tf_standard where keyword = 'DICOM_PRINT'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-23'), (select id from tf_standard where keyword = 'DICOM_LUT'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-23'), (select id from tf_standard where keyword = 'DICOM_GSDF'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-24'), (select id from tf_standard where keyword = 'DICOM_CMR'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-24'), (select id from tf_standard where keyword = 'DICOM_STORAGE'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-25'), (select id from tf_standard where keyword = 'DICOM_CMR'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-25'), (select id from tf_standard where keyword = 'DICOM_STORAGE'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-26'), (select id from tf_standard where keyword = 'DICOM_CMR'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-26'), (select id from tf_standard where keyword = 'DICOM_QR'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-27'), (select id from tf_standard where keyword = 'DICOM_STORAGE'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-27'), (select id from tf_standard where keyword = 'DICOM_CMR'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-27'), (select id from tf_standard where keyword = 'DICOM_QR'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-28'), (select id from tf_standard where keyword = 'HL7v2.3.1'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-29'), (select id from tf_standard where keyword = 'DICOM_KOS'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-29'), (select id from tf_standard where keyword = 'DICOM_STORAGE'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-30'), (select id from tf_standard where keyword = 'DICOM_KIN'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-30'), (select id from tf_standard where keyword = 'DICOM_QR'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-31'), (select id from tf_standard where keyword = 'DICOM_KOS'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-31'), (select id from tf_standard where keyword = 'DICOM_QR'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-35'), (select id from tf_standard where keyword = 'HL7v2.3.1'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-35'), (select id from tf_standard where keyword = 'DICOM_MPPS'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-36'), (select id from tf_standard where keyword = 'HL7v2.3.1'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-37'), (select id from tf_standard where keyword = 'DICOM_GPWL'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-38'), (select id from tf_standard where keyword = 'DICOM_GPSPS'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-39'), (select id from tf_standard where keyword = 'DICOM_GPPPS'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-40'), (select id from tf_standard where keyword = 'DICOM_GPPPS'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-41'), (select id from tf_standard where keyword = 'DICOM_GPSPS'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-42'), (select id from tf_standard where keyword = 'DICOM_GPPPS'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-43'), (select id from tf_standard where keyword = 'DICOM_STORAGE'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-44'), (select id from tf_standard where keyword = 'DICOM_QR'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-45'), (select id from tf_standard where keyword = 'DICOM_QR'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-46'), (select id from tf_standard where keyword = 'DICOM_GPWL'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-47'), (select id from tf_standard where keyword = 'DICOM_MEDIA_STORAGE_PROFILE'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-47'), (select id from tf_standard where keyword = 'DICOM_Suppl80'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-47'), (select id from tf_standard where keyword = 'DICOM_FILE_FORMAT'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-47'), (select id from tf_standard where keyword = 'DICOM_MEDIA_FORMAT'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-47'), (select id from tf_standard where keyword = 'XHTML_1.0'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-47'), (select id from tf_standard where keyword = 'XHTML_Basic'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-48'), (select id from tf_standard where keyword = 'HL7v2.4'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-49'), (select id from tf_standard where keyword = 'DICOM_IAN'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-50'), (select id from tf_standard where keyword = 'DICOM_STORAGE'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-51'), (select id from tf_standard where keyword = 'DICOM_BALCP'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-51'), (select id from tf_standard where keyword = 'DICOM_IOD'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-51'), (select id from tf_standard where keyword = 'DICOM_STORAGE'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-51'), (select id from tf_standard where keyword = 'DICOM_CMR'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-52'), (select id from tf_standard where keyword = 'DICOM_STORAGE'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-53'), (select id from tf_standard where keyword = 'DICOM_STORAGE'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-55'), (select id from tf_standard where keyword = 'WADO'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-59'), (select id from tf_standard where keyword = 'DICOM_MPPS'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-60'), (select id from tf_standard where keyword = 'DICOM_DCMR'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-60'), (select id from tf_standard where keyword = 'DICOM_MPPS'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-61'), (select id from tf_standard where keyword = 'DICOM_SIO'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-61'), (select id from tf_standard where keyword = 'DICOM_STORAGE'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-62'), (select id from tf_standard where keyword = 'DICOM_X_DOSE'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-62'), (select id from tf_standard where keyword = 'DICOM_SR'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-62'), (select id from tf_standard where keyword = 'DICOM_X_DOSE_TPL'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-62'), (select id from tf_standard where keyword = 'DICOM_CT_DOSE_TPL'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-62'), (select id from tf_standard where keyword = 'DICOM_DOSE_UC'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-63'), (select id from tf_standard where keyword = 'FTP_TLS'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-63'), (select id from tf_standard where keyword = 'DICOM_X_DOSE'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-63'), (select id from tf_standard where keyword = 'DICOM_FILE_FORMAT'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-63'), (select id from tf_standard where keyword = 'DICOM_X_DOSE_TPL'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-63'), (select id from tf_standard where keyword = 'DICOM_CT_DOSE_TPL'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-64'), (select id from tf_standard where keyword = 'DICOM_SR'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-64'), (select id from tf_standard where keyword = 'DICOM_QR'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-64'), (select id from tf_standard where keyword = 'DICOM_X_DOSE'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-65'), (select id from tf_standard where keyword = 'DICOM_SR'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-65'), (select id from tf_standard where keyword = 'DICOM_QR'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-65'), (select id from tf_standard where keyword = 'DICOM_X_DOSE'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-66'), (select id from tf_standard where keyword = 'DICOM_KOS'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-66'), (select id from tf_standard where keyword = 'DICOM_STORAGE'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-66'), (select id from tf_standard where keyword = 'DICOM_QR'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-66'), (select id from tf_standard where keyword = 'DICOM_TID'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'LAB-1'), (select id from tf_standard where keyword = 'HL7v2.5'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'LAB-2'), (select id from tf_standard where keyword = 'HL7v2.5'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'LAB-22'), (select id from tf_standard where keyword = 'HL7v2.5'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'LAB-21'), (select id from tf_standard where keyword = 'HL7v2.5'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'LAB-23'), (select id from tf_standard where keyword = 'HL7v2.5'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'LAB-26'), (select id from tf_standard where keyword = 'HL7v2.5'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'LAB-27'), (select id from tf_standard where keyword = 'HL7v2.5.1'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'LAB-28'), (select id from tf_standard where keyword = 'HL7v2.5.1'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'LAB-29'), (select id from tf_standard where keyword = 'HL7v2.5.1'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'LAB-3'), (select id from tf_standard where keyword = 'HL7v2.5'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'LAB-32'), (select id from tf_standard where keyword = 'HL7v2.5'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'LAB-35'), (select id from tf_standard where keyword = 'HL7v2.5.1'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'LAB-36'), (select id from tf_standard where keyword = 'HL7v2.5.1'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'LAB-4'), (select id from tf_standard where keyword = 'HL7v2.5'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'LAB-5'), (select id from tf_standard where keyword = 'HL7v2.5'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'LAB-51'), (select id from tf_standard where keyword = 'HL7v2.5'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'LAB-61'), (select id from tf_standard where keyword = 'HL7v2.5'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'LAB-62'), (select id from tf_standard where keyword = 'HL7v2.5'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'LAB-63'), (select id from tf_standard where keyword = 'HL7v2.5'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'LAB-30'), (select id from tf_standard where keyword = 'POCT1-A'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'LAB-31'), (select id from tf_standard where keyword = 'POCT1-A'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'LAB-32'), (select id from tf_standard where keyword = 'POCT1-A'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'CARD-7'), (select id from tf_standard where keyword = 'HL7v2.5'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'CARD-8'), (select id from tf_standard where keyword = 'HL7v2.5'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'PCD-1'), (select id from tf_standard where keyword = 'HL7v2.6'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'PCD-2'), (select id from tf_standard where keyword = 'HL7v2.6'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'PHARM-H1'), (select id from tf_standard where keyword = 'HL7v2.6'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'PHARM-H2'), (select id from tf_standard where keyword = 'HL7v2.6'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'PHARM-H3'), (select id from tf_standard where keyword = 'HL7v2.6'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'PHARM-H4'), (select id from tf_standard where keyword = 'HL7v2.6'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'PHARM-H5'), (select id from tf_standard where keyword = 'HL7v2.6'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'PHARM-H6'), (select id from tf_standard where keyword = 'HL7v2.6'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'PAT-10'), (select id from tf_standard where keyword = 'HL7v2.5.1'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'PAT-2'), (select id from tf_standard where keyword = 'HL7v2.5.1'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'PAT-3'), (select id from tf_standard where keyword = 'HL7v2.5.1'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'PAT-4'), (select id from tf_standard where keyword = 'HL7v2.5.1'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'PAT-5'), (select id from tf_standard where keyword = 'DICOM_MWL'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'PAT-6'), (select id from tf_standard where keyword = 'DICOM_Suppl122'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'PAT-6'), (select id from tf_standard where keyword = 'DICOM_MWL'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'CARD-1'), (select id from tf_standard where keyword = 'DICOM_MPPS'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'CARD-2'), (select id from tf_standard where keyword = 'DICOM_STORAGE'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'CARD-3'), (select id from tf_standard where keyword = 'DICOM_COMMIT'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'CARD-4'), (select id from tf_standard where keyword = 'DICOM_QR'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'CARD-4'), (select id from tf_standard where keyword = 'DICOM_STORAGE'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'CARD-5'), (select id from tf_standard where keyword = 'URL'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'CARD-5'), (select id from tf_standard where keyword = 'HTTP'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'CARD-5'), (select id from tf_standard where keyword = 'XML'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'CARD-5'), (select id from tf_standard where keyword = 'WSDL'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'CARD-5'), (select id from tf_standard where keyword = 'XHTML_1.0'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'CARD-5'), (select id from tf_standard where keyword = 'XHTML_Basic'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'CARD-6'), (select id from tf_standard where keyword = 'HTTP'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'CARD-6'), (select id from tf_standard where keyword = 'XML'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'CARD-6'), (select id from tf_standard where keyword = 'WSDL'));
-- complete on 02/09/2015
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'OASIS_WS_Notif', 'OASIS Web Services Notification Family of Standards', '', 'http://www.oasis-open.org/committees/tc_home.php?wg_abbrev=wsn', 4);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'OASIS_WS_BaseNotif', 'WS-BaseNotification 1.3 OASIS Standard', '', 'http://docs.oasis-open.org/wsn/wsn-ws_base_notification-1.3-spec-os.pdf', 4);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'OASIS_WS_BrokeredNotif', 'WS-BrokeredNotification 1.3 OASIS Standard', '', 'http://docs.oasis-open.org/wsn/wsn-ws_brokered_notification-1.3-spec-os.pdf', 4);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'OASIS_WS_Topics', 'WS-Topics 1.3 OASIS Standard', '', 'http://docs.oasis-open.org/wsn/wsn-ws_topics-1.3-spec-os.pdf', 4);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'ISO/TS21091', 'Health Informatics - Directory services for health care providers, subjects of care, and other entities (ISO/TS 21091)', '', '', 4);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'DSMLv2', 'DSMLv2', '', '', 4);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'OASIS_WS_BaseFault', 'WS-BaseFaults', '', '', 4);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'OASIS_WS_addressing', 'WS-Addressing OASIS Standard', '', '', 4);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'PDF_A', 'PDF/A ISO 19005-1 Document management - Electronic document file format for long-term preservation - Part1', '', '', 4);
INSERT INTO tf_standard(id, keyword, name, version, url, network_communication_type) values (nextval('tf_standard_id_seq'), 'HL7_CDA', 'HL7 CDA Release 2.0', '', '', 4);
UPDATE tf_standard set url = null where url = '';
UPDATE tf_standard set version = null where version = '';
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-52'), (select id from tf_standard where keyword = 'IHE_WS'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-52'), (select id from tf_standard where keyword = 'OASIS_WS_Notif'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-52'), (select id from tf_standard where keyword = 'OASIS_WS_BaseNotif'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-52'), (select id from tf_standard where keyword = 'OASIS_WS_BrokeredNotif'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-52'), (select id from tf_standard where keyword = 'OASIS_WS_Topics'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-53'), (select id from tf_standard where keyword = 'IHE_WS'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-53'), (select id from tf_standard where keyword = 'OASIS_WS_Notif'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-53'), (select id from tf_standard where keyword = 'OASIS_WS_BaseNotif'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-53'), (select id from tf_standard where keyword = 'OASIS_WS_BrokeredNotif'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-53'), (select id from tf_standard where keyword = 'OASIS_WS_Topics'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-54'), (select id from tf_standard where keyword = 'OASIS_WS_Notif'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-54'), (select id from tf_standard where keyword = 'OASIS_WS_BaseNotif'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-54'), (select id from tf_standard where keyword = 'OASIS_WS_BrokeredNotif'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-54'), (select id from tf_standard where keyword = 'OASIS_WS_Topics'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-54'), (select id from tf_standard where keyword = 'IHE_WS'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-56'), (select id from tf_standard where keyword = 'IHE_WS'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-56'), (select id from tf_standard where keyword = 'HL7_DT'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-57'), (select id from tf_standard where keyword = 'ebRIM'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-57'), (select id from tf_standard where keyword = 'ebRS'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-57'), (select id from tf_standard where keyword = 'IHE_WS'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-58'), (select id from tf_standard where keyword = 'ISO/TS21091'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-58'), (select id from tf_standard where keyword = 'IHE_WS'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-58'), (select id from tf_standard where keyword = 'LDAPv3'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-58'), (select id from tf_standard where keyword = 'DSMLv2'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-59'), (select id from tf_standard where keyword = 'ISO/TS21091'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-59'), (select id from tf_standard where keyword = 'IHE_WS'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-59'), (select id from tf_standard where keyword = 'LDAPv3'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-59'), (select id from tf_standard where keyword = 'DSMLv2'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-62'), (select id from tf_standard where keyword = 'ebRIM'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-62'), (select id from tf_standard where keyword = 'ebRS'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-62'), (select id from tf_standard where keyword = 'IHE_WS'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-64'), (select id from tf_standard where keyword = 'HL7v2.5'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-69'), (select id from tf_standard where keyword = 'IHE_WS'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-69'), (select id from tf_standard where keyword = 'OASIS_WS_Notif'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-69'), (select id from tf_standard where keyword = 'OASIS_WS_BaseNotif'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-69'), (select id from tf_standard where keyword = 'OASIS_WS_BrokeredNotif'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-69'), (select id from tf_standard where keyword = 'OASIS_WS_Topics'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-69'), (select id from tf_standard where keyword = 'OASIS_WS_BaseFault'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-69'), (select id from tf_standard where keyword = 'OASIS_WS_addressing'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-70'), (select id from tf_standard where keyword = 'IHE_WS'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-70'), (select id from tf_standard where keyword = 'OASIS_WS_Notif'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-70'), (select id from tf_standard where keyword = 'OASIS_WS_BaseNotif'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-70'), (select id from tf_standard where keyword = 'OASIS_WS_BrokeredNotif'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-70'), (select id from tf_standard where keyword = 'OASIS_WS_Topics'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-70'), (select id from tf_standard where keyword = 'OASIS_WS_BaseFault'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'ITI-70'), (select id from tf_standard where keyword = 'OASIS_WS_addressing'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-106'), (select id from tf_standard where keyword = 'HTTP'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-106'), (select id from tf_standard where keyword = 'URL'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-106'), (select id from tf_standard where keyword = 'XML'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-106'), (select id from tf_standard where keyword = 'WSDL'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-67'), (select id from tf_standard where keyword = 'DICOM_STORAGE'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-68'), (select id from tf_standard where keyword = 'DICOM_KOS'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-68'), (select id from tf_standard where keyword = 'WADO'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-68'), (select id from tf_standard where keyword = 'HL7_CDA'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-68'), (select id from tf_standard where keyword = 'PDF_A'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-68'), (select id from tf_standard where keyword = 'DICOM_CMR'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-69'), (select id from tf_standard where keyword = 'XOP'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-69'), (select id from tf_standard where keyword = 'ebRIM'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-69'), (select id from tf_standard where keyword = 'ebRS'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-69'), (select id from tf_standard where keyword = 'IHE_WS'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-69'), (select id from tf_standard where keyword = 'ITI_TF3'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-69'), (select id from tf_standard where keyword = 'MTOM'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-74'), (select id from tf_standard where keyword = 'DICOM_STORAGE'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-75'), (select id from tf_standard where keyword = 'XOP'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-75'), (select id from tf_standard where keyword = 'ebRIM'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-75'), (select id from tf_standard where keyword = 'ebRS'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-75'), (select id from tf_standard where keyword = 'IHE_WS'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-75'), (select id from tf_standard where keyword = 'ITI_TF3'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-75'), (select id from tf_standard where keyword = 'MTOM'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-76'), (select id from tf_standard where keyword = 'DICOM_QR'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-77'), (select id from tf_standard where keyword = 'DICOM_QR'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-78'), (select id from tf_standard where keyword = 'HL7v2.5.1'));
INSERT INTO tf_transaction_standard (transaction_id, standard_id) values ((select id from tf_transaction where keyword = 'RAD-79'), (select id from tf_standard where keyword = 'HL7v2.5.1'));