drop table tm_validation_logs;
drop table tm_object_file_method;
drop table tm_object_method_parameter;
drop table tm_object_parameter_validator;
drop table tm_object_method_validator;
drop table tm_object_class_validator;
drop table tm_validation_logs_aud;
drop table tm_object_file_method_aud;
drop table tm_object_method_parameter_aud;
drop table tm_object_parameter_validator_aud;
drop table tm_object_method_validator_aud;
drop table tm_object_class_validator_aud;
alter table tm_object_file_type_aud add validate boolean DEFAULT false;
update tm_object_file_type set validate = false;
update tm_object_file_type set validate = true where keyword='CDA';
update tm_object_file_type set validate = true where keyword='DICOM';
update tm_object_file_type set validate = true where keyword='XML';
update tm_object_file_type set validate = true where keyword='PDF';
update tm_object_file_type set validate = true where keyword='HL7';
